package com.QS.AppQuickSolutions.enums;

public enum PartState {

    DESARROLLANDO,
    EN_PLEGADOR,
    EN_FABRICA,
    DEVOLUCION_FUERA_DE_MEDIDA,
    FALTANTE,
    CONFECCIONADO,
    PINTADO,
    REPINTANDO_POR_GOLPE_O_RAYON,
    EMBALADO,
    EN_DEPOSITO,
    DESPACHADO,
    REPARACION_PENDIENTE;
}
